### ISSUE TITLE
Rename didn't work.

### ISSUE THREAD

**Issue by timturing** [j3soon/arxiv-utils#33]
I was really excited to use this extension in Google Chrome (version info:119.0.6045.160 (Official Build) (64-bit)), but it turns out the rename option didn't work at all:
![test](https://github.com/j3soon/arxiv-utils/assets/86722018/9df999c7-fb19-4273-bc04-aa968451ee34)

The filename in the tab changed, but it didn't work when I clicked the direct download option. The option is default, and I've tried to close the arxiv page and open it again for several times. Could you help me with that?

**Comment by j3soon** [comment]
I just tested this on Windows using Chrome (Version 119.0.6045.160 (Official Build) (64-bit)) to download this paper: https://arxiv.org/abs/2202.05262

However, the direct download feature works well on my computer. Therefore I cannot reproduce your issue.

Could you try using a new profile without other extensions? I think it may be due to conflicts with other extensions.

**Comment by timturing** [comment]
Thanks a lot! It works now after I banned other extensions. Actually, it's due to another extension designed for download too. I leave [it](https://chromewebstore.google.com/detail/aix-downloaderpicturevide/ibdfeimkglcmdejppabkaidpippniiob) here if this could help you to make the extension more robust. Thanks again!
