### ISSUE TITLE
Tab names not being renamed in firefox for PDF on arxiv for new papers

### ISSUE THREAD

**Issue by akhilkedia** [j3soon/arxiv-utils#40]
**Describe the bug**
Tab names in firefox for PDF on arxiv are no longer being renamed to paper title. This bug only occurs for new papers on arxiv after some recent date (eg  https://arxiv.org/abs/2402.12354), tab names on older papers (eg https://arxiv.org/abs/1902.04760) seem to be renamed correctly.

**To Reproduce**
1. Go to https://arxiv.org/abs/2402.12354
2. Click on [View PDF](https://arxiv.org/pdf/2402.12354)
3. Tab is not renamed to paper title

**Expected behavior**
Tab should be renamed to paper title for the pdf page. 

**Screenshots**
- Developer Console on the "abs" page shows "[arXiv-utils] Set document title to: LoRA+: Efficient Low Rank Adaptation of Large Models | Abstract.". 
  - On clicking view pdf, only the following is printed in the console "Partitioned cookie or storage access was provided to “https://arxiv.org/pdf/2402.12354” because it is loaded in the third-party context and dynamic state partitioning is enabled.
PDF 667dcc7fab22827c75d0e4aa0b17241d [1.5 pdfTeX-1.40.25 / LaTeX with hyperref] (PDF.js: 4.1.342 [e384df6f1])"
- Inspect the background script logs shows no errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 125.0.3

Bug was successfully reproduced in a new browser profile with no other extensions installed.  The "abs" page on arxiv is being renamed successfully. Clicking the extension icon to open the pdf from the abs page also successfully renamed the pdf.

Thank you so much for making this extension! I will try to poke around the code to see if I can identify the cause of this issue..

**Comment by j3soon** [comment]
Thanks for the bug report. I can reproduce it on my end.

I believe it's due to the arXiv site link change from `Download PDF` to `View PDF`. The new `View PDF` link seems to point to a different URL (without trailing `.pdf`), which isn't re-directed to the custom PDF viewer.

Currently, this issue can be bypassed by clicking the extension button (with arxiv icon) instead of clicking `View PDF`.

If you want to open a PR, I suggest you look into the redirection pattern here: https://github.com/j3soon/arxiv-utils/blob/e0ccee73c70d90b63467e78d2bd7578a3730ebe0/firefox/background.js#L6-L14

I think the redirection pattern need to be updated.

**Comment by zinhuofc** [comment]
you don't want to go back to developing alltrans, you abandoned your users very well
