### ISSUE TITLE
Why history is needed ?

### ISSUE THREAD

**Issue by wickcode** [j3soon/arxiv-utils#41]
**Describe the bug**
I was just wondering why does this extension in chrome required to read browser history ? 

**To Reproduce**
![image](https://github.com/j3soon/arxiv-utils/assets/77705475/e390079a-fd0c-4bb3-a2ec-286c2a2dfba3)

**Expected behavior**
If this access is required only for stability and no data is being collected. I think I would appreciate that the webstore page clarifies this.

Thank you for the amazing plugin. I use it regularly and would like to continue using it.

**Comment by fepegar** [comment]
I was also surprised to see this today!

**Comment by j3soon** [comment]
Thanks for bringing up this issue. Privacy is extremely important to me, which is why I don't collect any user data and avoid using any external APIs. The design philosophy is that when you are reading an arXiv paper, no other people or external sites should be aware of what you're reading. To maintain this level of privacy, I avoid integrating even trusted services like Semantic Scholar or PapersWithCode, which may seem a bit too paranoid.

Back to your question, the warning `Read your browsing history` is actually nothing new. If I recall correctly, the very first version of this extension has this warning. This is due to the use of `tabs` for accessing webpage tab titles.

>`"tabs"`
>
> Gives access to privileged fields of the Tab objects used by several APIs, including [`chrome.tabs`](https://developer.chrome.com/docs/extensions/reference/api/tabs) and [`chrome.windows`](https://developer.chrome.com/docs/extensions/reference/api/windows). You usually don't need to declare this permission to use those APIs.
> Warning displayed: _Read your browsing history._
>
> -- [Chrome Extensions Permissions Reference](https://developer.chrome.com/docs/extensions/reference/permissions-list) 

More detailed reason can be seen below:

> **The "tabs" permission**
> 
> This permission does not give access to the `chrome.tabs` namespace. Instead, it grants an extension the ability to call [`tabs.query()`](https://developer.chrome.com/docs/extensions/reference/api/tabs#method-query) against four sensitive properties on [`tabs.Tab`](https://developer.chrome.com/docs/extensions/reference/api/tabs#type-Tab) instances: `url`, `pendingUrl`, `title`, and `favIconUrl`.
>
> -- [Chrome Extensions `chrome.tabs` API Reference](https://developer.chrome.com/docs/extensions/reference/api/tabs)

If you still have doubt, please refer to the source code: https://github.com/j3soon/arxiv-utils/blob/647257191b97697106edf018c1c0f91297b62afb/chrome/background.js#L119

<hr>

I try to keep the permission usages as clear as possible (see https://github.com/j3soon/arxiv-utils/tree/master?tab=readme-ov-file#privacy-policy). But currently the section is more developer-oriented instead of user-oriented.

I may try to improve the permission usage sections to be more user-friendly if I have time...

**Comment by wickcode** [comment]
thanks for the clarification. :)
